<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="HP Unified Functional Testing" productVer="12.0" os="Windows 7" host="RD-ZHANGYANG"><DocLocation><![CDATA[D:\QTP_EC10\009_EC主界面_销售助手_正常新建微信计划_验证右下角弹窗]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[009_EC主界面_销售助手_正常新建微信计划_验证右下角弹窗]]></DName>
<Res><![CDATA[Report]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj ><![CDATA[Output to global sheet]]></Obj>
<Details ><![CDATA[Name: 客户姓名
Value: caishifu]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:02]]></Time>
<TimeTick>1534744802</TimeTick>
<NodeArgs eType="User" icon="3" nRep="6" status="Information" >
<Disp><![CDATA[Output to global sheet]]></Disp>
</NodeArgs>
</Step>
<Step rID="T4">
<Obj ><![CDATA[Output to global sheet]]></Obj>
<Details ><![CDATA[Name: 计划标题
Value: 测试标题]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:02]]></Time>
<TimeTick>1534744802</TimeTick>
<NodeArgs eType="User" icon="3" nRep="7" status="Information" >
<Disp><![CDATA[Output to global sheet]]></Disp>
</NodeArgs>
</Step>
<Step rID="T5">
<Obj ><![CDATA[Output to global sheet]]></Obj>
<Details ><![CDATA[Name: 计划内容
Value: 测试内容]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:02]]></Time>
<TimeTick>1534744802</TimeTick>
<NodeArgs eType="User" icon="3" nRep="8" status="Information" >
<Disp><![CDATA[Output to global sheet]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj ><![CDATA[This test is run in the EC-QA  environment by ZhangYang on RD-ZHANGYANG]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:02]]></Time>
<TimeTick>1534744802</TimeTick>
<NodeArgs eType="User" icon="3" nRep="9" status="Information" >
<Disp><![CDATA[This test is run in the EC-QA  environment by ZhangYang on RD-ZHANGYANG]]></Disp>
</NodeArgs>
</Step>
<DIter rID="T7" iterID="1" >
<Action rID="T8">
<AName><![CDATA[Action1]]></AName>
<Action rID="T9">
<AName><![CDATA[EC_10主界面 [EC10_主面板]]]></AName>
<Step rID="T10">
<Obj ><![CDATA[Action Run: 进入销售助手]]></Obj>
<Details ><![CDATA[Data Row: 8]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:03]]></Time>
<TimeTick>1534744803</TimeTick>
<NodeArgs eType="User" icon="3" nRep="13" status="Information" >
<Disp><![CDATA[Action Run: 进入销售助手]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[EC10.0]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:05]]></Time>
<TimeTick>1534744805</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[销售助手入口.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:05]]></Time>
<TimeTick>1534744805</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="16" Source="EC_10主界面 [EC10_主面板]" SourceLine="-1" >
<Disp><![CDATA[销售助手入口.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="15" Source="EC_10主界面 [EC10_主面板]" SourceLine="-1" >
<Disp><![CDATA[EC10.0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[销售助手]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:05]]></Time>
<TimeTick>1534744805</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[销售助手页检查点.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:05]]></Time>
<TimeTick>1534744805</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" Source="EC_10主界面 [EC10_主面板]" SourceLine="-1" >
<Disp><![CDATA[销售助手页检查点.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="17" Source="EC_10主界面 [EC10_主面板]" SourceLine="-1" >
<Disp><![CDATA[销售助手]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj ><![CDATA[销售助手页是否已经打开]]></Obj>
<Details ><![CDATA[已经打开！]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:05]]></Time>
<TimeTick>1534744805</TimeTick>
<NodeArgs eType="User" icon="3" nRep="19" status="Passed" Source="EC_10主界面 [EC10_主面板]" SourceLine="-1" >
<Disp><![CDATA[销售助手页是否已经打开]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2018/8/20 - 14:00:03" eTime="2018/8/20 - 14:00:05" passed="1" failed="0" warnings="0" ><Param ><ParamName><![CDATA[Action]]></ParamName><ParamVal><![CDATA[进入销售助手]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="6" nRep="12" status="Passed" >
<Disp><![CDATA[EC_10主界面 [EC10_主面板] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T16">
<AName><![CDATA[Action1 [EC10_销售助手]]]></AName>
<Step rID="T17">
<Obj ><![CDATA[Action Run: 新建微信计划]]></Obj>
<Details ><![CDATA[Data Row: 5]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:07]]></Time>
<TimeTick>1534744807</TimeTick>
<NodeArgs eType="User" icon="3" nRep="22" status="Information" >
<Disp><![CDATA[Action Run: 新建微信计划]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[销售助手]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:08]]></Time>
<TimeTick>1534744808</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[新建计划.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:08]]></Time>
<TimeTick>1534744808</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="24" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[新建计划.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[新建计划.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:08]]></Time>
<TimeTick>1534744808</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="26" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[新建计划.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[微信计划创建入口.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:09]]></Time>
<TimeTick>1534744809</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="28" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[微信计划创建入口.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="23" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[销售助手]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[新建计划]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:10]]></Time>
<TimeTick>1534744810</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[计划标题.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:10]]></Time>
<TimeTick>1534744810</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="30" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[计划标题.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[计划标题.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["测试标题20180820140010"]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:11]]></Time>
<TimeTick>1534744811</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="32" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[计划标题.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[QQ计划内容.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["测试内容"]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:12]]></Time>
<TimeTick>1534744812</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="34" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[QQ计划内容.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[添加客户.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:13]]></Time>
<TimeTick>1534744813</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="36" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[添加客户.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="29" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[新建计划]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[选择客户]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:15]]></Time>
<TimeTick>1534744815</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[搜索客户.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["caishifu"]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:15]]></Time>
<TimeTick>1534744815</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="39" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[搜索客户.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[选择客户.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[150, 108, 0]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:15]]></Time>
<TimeTick>1534744815</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="41" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[选择客户.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[确定.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:15]]></Time>
<TimeTick>1534744815</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="43" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[确定.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="38" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[选择客户]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[新建计划]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:16]]></Time>
<TimeTick>1534744816</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[时间.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:16]]></Time>
<TimeTick>1534744816</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="46" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[时间.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[选择当前时间.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:16]]></Time>
<TimeTick>1534744816</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="48" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[选择当前时间.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[保存计划.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:16]]></Time>
<TimeTick>1534744816</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="50" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[保存计划.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[保存成功.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:17]]></Time>
<TimeTick>1534744817</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="51" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[保存成功.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="45" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[新建计划]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj ><![CDATA[是否正常保存短信计划?]]></Obj>
<Details ><![CDATA[正常保存!]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:17]]></Time>
<TimeTick>1534744817</TimeTick>
<NodeArgs eType="User" icon="3" nRep="52" status="Passed" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[是否正常保存短信计划?]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2018/8/20 - 14:00:06" eTime="2018/8/20 - 14:00:17" passed="1" failed="0" warnings="0" ><Param ><ParamName><![CDATA[Action]]></ParamName><ParamVal><![CDATA[新建微信计划]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="6" nRep="21" status="Passed" >
<Disp><![CDATA[Action1 [EC10_销售助手] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T37">
<AName><![CDATA[Action1 [EC10_销售助手]]]></AName>
<Step rID="T38">
<Obj ><![CDATA[Action Run: 关闭销售助手页]]></Obj>
<Details ><![CDATA[Data Row: 7]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:18]]></Time>
<TimeTick>1534744818</TimeTick>
<NodeArgs eType="User" icon="3" nRep="55" status="Information" >
<Disp><![CDATA[Action Run: 关闭销售助手页]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[销售助手]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:19]]></Time>
<TimeTick>1534744819</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[关闭页面按钮.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:19]]></Time>
<TimeTick>1534744819</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="57" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[关闭页面按钮.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[关闭页面按钮.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:20]]></Time>
<TimeTick>1534744820</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="59" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[关闭页面按钮.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[关闭页面按钮.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:41]]></Time>
<TimeTick>1534744841</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="62" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[关闭页面按钮.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="56" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[销售助手]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj ><![CDATA[是否正常关闭销售助手页]]></Obj>
<Details ><![CDATA[已经关闭!]]></Details>
<Time><![CDATA[2018/8/20 - 14:00:41]]></Time>
<TimeTick>1534744841</TimeTick>
<NodeArgs eType="User" icon="3" nRep="63" status="Passed" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[是否正常关闭销售助手页]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2018/8/20 - 14:00:18" eTime="2018/8/20 - 14:00:41" passed="1" failed="0" warnings="0" ><Param ><ParamName><![CDATA[Action]]></ParamName><ParamVal><![CDATA[关闭销售助手页]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="6" nRep="54" status="Passed" >
<Disp><![CDATA[Action1 [EC10_销售助手] Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="2018/8/20 - 14:00:02" eTime="2018/8/20 - 14:00:41" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="4" nRep="10" status="Passed" >
<Disp><![CDATA[009_EC主界面_销售助手_正常新建微信计划_验证右下角弹窗 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="2018/8/20 - 14:00:00" eTime="2018/8/20 - 14:00:41" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test 009_EC主界面_销售助手_正常新建微信计划_验证右下角弹窗 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>