<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="HP Unified Functional Testing" productVer="12.0" os="Windows 7" host="RD-ZHANGYANG"><DocLocation><![CDATA[D:\QTP_EC10\002_登陆页面_有效账户密码直接登录]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[002_登陆页面_有效账户密码直接登录]]></DName>
<Res><![CDATA[Report]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="62" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj ><![CDATA[This test is run in the EC-QA  environment by ZhangYang on RD-ZHANGYANG]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/17 - 16:25:58]]></Time>
<TimeTick>1534494358</TimeTick>
<NodeArgs eType="User" icon="63" nRep="6" status="Information" >
<Disp><![CDATA[This test is run in the EC-QA  environment by ZhangYang on RD-ZHANGYANG]]></Disp>
</NodeArgs>
</Step>
<DIter rID="T4" iterID="1" >
<Action rID="T5">
<AName><![CDATA[Action1]]></AName>
<Action rID="T6">
<AName><![CDATA[Action1 [EC10_登录页面]]]></AName>
<Step rID="T7">
<Obj ><![CDATA[Action Run: 输入登录账号]]></Obj>
<Details ><![CDATA[Data Row: 1]]></Details>
<Time><![CDATA[2018/8/17 - 16:25:59]]></Time>
<TimeTick>1534494359</TimeTick>
<NodeArgs eType="User" icon="63" nRep="10" status="Information" >
<Disp><![CDATA[Action Run: 输入登录账号]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[EC10登录界面_操作项]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:00]]></Time>
<TimeTick>1534494360</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[登录按钮.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:00]]></Time>
<TimeTick>1534494360</TimeTick>
<NodeArgs eType="Replay" icon="68" nRep="12" Source="Action1 [EC10_登录页面]" SourceLine="-1" >
<Disp><![CDATA[登录按钮.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="67" nRep="11" Source="Action1 [EC10_登录页面]" SourceLine="-1" >
<Disp><![CDATA[EC10登录界面_操作项]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj ><![CDATA[Verify Page - 登录界面]]></Obj>
<Details ><![CDATA[At 登录界面 Page]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:00]]></Time>
<TimeTick>1534494360</TimeTick>
<NodeArgs eType="User" icon="63" nRep="13" status="Passed" Source="Action1 [EC10_登录页面]" SourceLine="-1" >
<Disp><![CDATA[Verify Page - 登录界面]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[EC10登录界面_操作项]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:00]]></Time>
<TimeTick>1534494360</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[账号输入框.Type]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:00]]></Time>
<TimeTick>1534494360</TimeTick>
<NodeArgs eType="Replay" icon="68" nRep="16" Source="Action1 [EC10_登录页面]" SourceLine="-1" >
<Disp><![CDATA[账号输入框.Type]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="67" nRep="15" Source="Action1 [EC10_登录页面]" SourceLine="-1" >
<Disp><![CDATA[EC10登录界面_操作项]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2018/8/17 - 16:25:59" eTime="2018/8/17 - 16:26:00" passed="1" failed="0" warnings="0" ><Param ><ParamName><![CDATA[Action]]></ParamName><ParamVal><![CDATA[输入登录账号]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="66" nRep="9" status="Passed" >
<Disp><![CDATA[Action1 [EC10_登录页面] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T13">
<AName><![CDATA[Action1 [EC10_登录页面]]]></AName>
<Step rID="T14">
<Obj ><![CDATA[Action Run: 输入登录密码]]></Obj>
<Details ><![CDATA[Data Row: 2]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:02]]></Time>
<TimeTick>1534494362</TimeTick>
<NodeArgs eType="User" icon="63" nRep="19" status="Information" >
<Disp><![CDATA[Action Run: 输入登录密码]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[EC10登录界面_操作项]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:03]]></Time>
<TimeTick>1534494363</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[登录按钮.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:03]]></Time>
<TimeTick>1534494363</TimeTick>
<NodeArgs eType="Replay" icon="68" nRep="21" Source="Action1 [EC10_登录页面]" SourceLine="-1" >
<Disp><![CDATA[登录按钮.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="67" nRep="20" Source="Action1 [EC10_登录页面]" SourceLine="-1" >
<Disp><![CDATA[EC10登录界面_操作项]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj ><![CDATA[Verify Page - 登录界面]]></Obj>
<Details ><![CDATA[At 登录界面 Page]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:03]]></Time>
<TimeTick>1534494363</TimeTick>
<NodeArgs eType="User" icon="63" nRep="22" status="Passed" Source="Action1 [EC10_登录页面]" SourceLine="-1" >
<Disp><![CDATA[Verify Page - 登录界面]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[EC10登录界面_操作项]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:03]]></Time>
<TimeTick>1534494363</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[账号密码输入框.Type]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:03]]></Time>
<TimeTick>1534494363</TimeTick>
<NodeArgs eType="Replay" icon="68" nRep="25" Source="Action1 [EC10_登录页面]" SourceLine="-1" >
<Disp><![CDATA[账号密码输入框.Type]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="67" nRep="24" Source="Action1 [EC10_登录页面]" SourceLine="-1" >
<Disp><![CDATA[EC10登录界面_操作项]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2018/8/17 - 16:26:02" eTime="2018/8/17 - 16:26:03" passed="1" failed="0" warnings="0" ><Param ><ParamName><![CDATA[Action]]></ParamName><ParamVal><![CDATA[输入登录密码]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="66" nRep="18" status="Passed" >
<Disp><![CDATA[Action1 [EC10_登录页面] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T20">
<AName><![CDATA[Action1 [EC10_登录页面]]]></AName>
<Step rID="T21">
<Obj ><![CDATA[Action Run: 点击登录按钮进行登录]]></Obj>
<Details ><![CDATA[Data Row: 3]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:04]]></Time>
<TimeTick>1534494364</TimeTick>
<NodeArgs eType="User" icon="63" nRep="28" status="Information" >
<Disp><![CDATA[Action Run: 点击登录按钮进行登录]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[EC10登录界面_操作项]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:06]]></Time>
<TimeTick>1534494366</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[登录按钮.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:06]]></Time>
<TimeTick>1534494366</TimeTick>
<NodeArgs eType="Replay" icon="68" nRep="30" Source="Action1 [EC10_登录页面]" SourceLine="-1" >
<Disp><![CDATA[登录按钮.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="67" nRep="29" Source="Action1 [EC10_登录页面]" SourceLine="-1" >
<Disp><![CDATA[EC10登录界面_操作项]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj ><![CDATA[Verify Page - 登录界面]]></Obj>
<Details ><![CDATA[At 登录界面 Page]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:06]]></Time>
<TimeTick>1534494366</TimeTick>
<NodeArgs eType="User" icon="63" nRep="31" status="Passed" Source="Action1 [EC10_登录页面]" SourceLine="-1" >
<Disp><![CDATA[Verify Page - 登录界面]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[EC10登录界面_操作项]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:06]]></Time>
<TimeTick>1534494366</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[登录按钮.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:06]]></Time>
<TimeTick>1534494366</TimeTick>
<NodeArgs eType="Replay" icon="68" nRep="34" Source="Action1 [EC10_登录页面]" SourceLine="-1" >
<Disp><![CDATA[登录按钮.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="67" nRep="33" Source="Action1 [EC10_登录页面]" SourceLine="-1" >
<Disp><![CDATA[EC10登录界面_操作项]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2018/8/17 - 16:26:04" eTime="2018/8/17 - 16:26:06" passed="1" failed="0" warnings="0" ><Param ><ParamName><![CDATA[Action]]></ParamName><ParamVal><![CDATA[点击登录按钮进行登录]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="66" nRep="27" status="Passed" >
<Disp><![CDATA[Action1 [EC10_登录页面] Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="2018/8/17 - 16:25:58" eTime="2018/8/17 - 16:26:06" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="65" nRep="8" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="64" nRep="7" status="Passed" >
<Disp><![CDATA[002_登陆页面_有效账户密码直接登录 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="2018/8/17 - 16:25:56" eTime="2018/8/17 - 16:26:06" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="61" nRep="3" status="Passed" >
<Disp><![CDATA[Test 002_登陆页面_有效账户密码直接登录 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>