<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="HP Unified Functional Testing" productVer="12.0" os="Windows 7" host="RD-ZHANGYANG"><DocLocation><![CDATA[D:\QTP_EC10\008_EC主界面_销售助手_正常新建邮件计划_验证右下角弹窗]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[008_EC主界面_销售助手_正常新建邮件计划_验证右下角弹窗]]></DName>
<Res><![CDATA[Report]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="13" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj ><![CDATA[Output to global sheet]]></Obj>
<Details ><![CDATA[Name: 客户姓名
Value: caishifu]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:31]]></Time>
<TimeTick>1534744711</TimeTick>
<NodeArgs eType="User" icon="14" nRep="6" status="Information" >
<Disp><![CDATA[Output to global sheet]]></Disp>
</NodeArgs>
</Step>
<Step rID="T4">
<Obj ><![CDATA[Output to global sheet]]></Obj>
<Details ><![CDATA[Name: 邮件主题
Value: 测试邮件]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:31]]></Time>
<TimeTick>1534744711</TimeTick>
<NodeArgs eType="User" icon="14" nRep="7" status="Information" >
<Disp><![CDATA[Output to global sheet]]></Disp>
</NodeArgs>
</Step>
<Step rID="T5">
<Obj ><![CDATA[Output to global sheet]]></Obj>
<Details ><![CDATA[Name: 计划标题
Value: 测试标题]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:31]]></Time>
<TimeTick>1534744711</TimeTick>
<NodeArgs eType="User" icon="14" nRep="8" status="Information" >
<Disp><![CDATA[Output to global sheet]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj ><![CDATA[Output to global sheet]]></Obj>
<Details ><![CDATA[Name: 计划内容
Value: 测试内容]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:31]]></Time>
<TimeTick>1534744711</TimeTick>
<NodeArgs eType="User" icon="14" nRep="9" status="Information" >
<Disp><![CDATA[Output to global sheet]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj ><![CDATA[This test is run in the EC-QA  environment by ZhangYang on RD-ZHANGYANG]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:31]]></Time>
<TimeTick>1534744711</TimeTick>
<NodeArgs eType="User" icon="14" nRep="10" status="Information" >
<Disp><![CDATA[This test is run in the EC-QA  environment by ZhangYang on RD-ZHANGYANG]]></Disp>
</NodeArgs>
</Step>
<DIter rID="T8" iterID="1" >
<Action rID="T9">
<AName><![CDATA[Action1]]></AName>
<Action rID="T10">
<AName><![CDATA[EC_10主界面 [EC10_主面板]]]></AName>
<Step rID="T11">
<Obj ><![CDATA[Action Run: 进入销售助手]]></Obj>
<Details ><![CDATA[Data Row: 8]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:33]]></Time>
<TimeTick>1534744713</TimeTick>
<NodeArgs eType="User" icon="14" nRep="14" status="Information" >
<Disp><![CDATA[Action Run: 进入销售助手]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[EC10.0]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:34]]></Time>
<TimeTick>1534744714</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[销售助手入口.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:34]]></Time>
<TimeTick>1534744714</TimeTick>
<NodeArgs eType="Replay" icon="19" nRep="17" Source="EC_10主界面 [EC10_主面板]" SourceLine="-1" >
<Disp><![CDATA[销售助手入口.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="18" nRep="16" Source="EC_10主界面 [EC10_主面板]" SourceLine="-1" >
<Disp><![CDATA[EC10.0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[销售助手]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:34]]></Time>
<TimeTick>1534744714</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[销售助手页检查点.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:34]]></Time>
<TimeTick>1534744714</TimeTick>
<NodeArgs eType="Replay" icon="19" nRep="19" Source="EC_10主界面 [EC10_主面板]" SourceLine="-1" >
<Disp><![CDATA[销售助手页检查点.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="18" nRep="18" Source="EC_10主界面 [EC10_主面板]" SourceLine="-1" >
<Disp><![CDATA[销售助手]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj ><![CDATA[销售助手页是否已经打开]]></Obj>
<Details ><![CDATA[已经打开！]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:34]]></Time>
<TimeTick>1534744714</TimeTick>
<NodeArgs eType="User" icon="14" nRep="20" status="Passed" Source="EC_10主界面 [EC10_主面板]" SourceLine="-1" >
<Disp><![CDATA[销售助手页是否已经打开]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2018/8/20 - 13:58:32" eTime="2018/8/20 - 13:58:35" passed="1" failed="0" warnings="0" ><Param ><ParamName><![CDATA[Action]]></ParamName><ParamVal><![CDATA[进入销售助手]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="17" nRep="13" status="Passed" >
<Disp><![CDATA[EC_10主界面 [EC10_主面板] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T17">
<AName><![CDATA[Action1 [EC10_销售助手]]]></AName>
<Step rID="T18">
<Obj ><![CDATA[Action Run: 新建邮件计划]]></Obj>
<Details ><![CDATA[Data Row: 4]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:36]]></Time>
<TimeTick>1534744716</TimeTick>
<NodeArgs eType="User" icon="14" nRep="23" status="Information" >
<Disp><![CDATA[Action Run: 新建邮件计划]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[销售助手]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:38]]></Time>
<TimeTick>1534744718</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[新建计划.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:38]]></Time>
<TimeTick>1534744718</TimeTick>
<NodeArgs eType="Replay" icon="19" nRep="25" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[新建计划.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[新建计划.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:38]]></Time>
<TimeTick>1534744718</TimeTick>
<NodeArgs eType="Replay" icon="19" nRep="27" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[新建计划.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[邮件计划创建入口.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:38]]></Time>
<TimeTick>1534744718</TimeTick>
<NodeArgs eType="Replay" icon="19" nRep="29" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[邮件计划创建入口.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="18" nRep="24" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[销售助手]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[新建计划]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:39]]></Time>
<TimeTick>1534744719</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[计划标题.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:39]]></Time>
<TimeTick>1534744719</TimeTick>
<NodeArgs eType="Replay" icon="19" nRep="31" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[计划标题.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[计划标题.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["测试标题20180820135839"]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:41]]></Time>
<TimeTick>1534744721</TimeTick>
<NodeArgs eType="Replay" icon="19" nRep="33" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[计划标题.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[邮件计划主题.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["测试标题20180820135841"]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:42]]></Time>
<TimeTick>1534744722</TimeTick>
<NodeArgs eType="Replay" icon="19" nRep="35" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[邮件计划主题.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[邮件内容.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["测试标题20180820135842"]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:43]]></Time>
<TimeTick>1534744723</TimeTick>
<NodeArgs eType="Replay" icon="19" nRep="37" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[邮件内容.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[邮件计划添加客户.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:44]]></Time>
<TimeTick>1534744724</TimeTick>
<NodeArgs eType="Replay" icon="19" nRep="39" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[邮件计划添加客户.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="18" nRep="30" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[新建计划]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[选择客户]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:46]]></Time>
<TimeTick>1534744726</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[搜索客户.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["caishifu"]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:46]]></Time>
<TimeTick>1534744726</TimeTick>
<NodeArgs eType="Replay" icon="19" nRep="42" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[搜索客户.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[选择客户.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[150, 108, 0]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:46]]></Time>
<TimeTick>1534744726</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="44" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[选择客户.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[确定.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:46]]></Time>
<TimeTick>1534744726</TimeTick>
<NodeArgs eType="Replay" icon="19" nRep="46" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[确定.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="18" nRep="41" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[选择客户]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[新建计划]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:47]]></Time>
<TimeTick>1534744727</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[邮件计划时间.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:47]]></Time>
<TimeTick>1534744727</TimeTick>
<NodeArgs eType="Replay" icon="19" nRep="49" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[邮件计划时间.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[选择当前时间.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:47]]></Time>
<TimeTick>1534744727</TimeTick>
<NodeArgs eType="Replay" icon="19" nRep="51" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[选择当前时间.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[保存计划.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:47]]></Time>
<TimeTick>1534744727</TimeTick>
<NodeArgs eType="Replay" icon="19" nRep="53" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[保存计划.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="18" nRep="48" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[新建计划]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[SystemNoticePanelFrm]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:48]]></Time>
<TimeTick>1534744728</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[邮件计划执行校验.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:48]]></Time>
<TimeTick>1534744728</TimeTick>
<NodeArgs eType="Replay" icon="19" nRep="55" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[邮件计划执行校验.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="18" nRep="54" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[SystemNoticePanelFrm]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj ><![CDATA[是否正常执行邮件计划?]]></Obj>
<Details ><![CDATA[正常执行!]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:48]]></Time>
<TimeTick>1534744728</TimeTick>
<NodeArgs eType="User" icon="14" nRep="56" status="Passed" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[是否正常执行邮件计划?]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[SystemNoticePanelFrm]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:49]]></Time>
<TimeTick>1534744729</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[关闭弹屏.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:49]]></Time>
<TimeTick>1534744729</TimeTick>
<NodeArgs eType="Replay" icon="19" nRep="59" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[关闭弹屏.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="18" nRep="58" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[SystemNoticePanelFrm]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2018/8/20 - 13:58:36" eTime="2018/8/20 - 13:58:49" passed="1" failed="0" warnings="0" ><Param ><ParamName><![CDATA[Action]]></ParamName><ParamVal><![CDATA[新建邮件计划]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="17" nRep="22" status="Passed" >
<Disp><![CDATA[Action1 [EC10_销售助手] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T42">
<AName><![CDATA[Action1 [EC10_销售助手]]]></AName>
<Step rID="T43">
<Obj ><![CDATA[Action Run: 关闭销售助手页]]></Obj>
<Details ><![CDATA[Data Row: 7]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:50]]></Time>
<TimeTick>1534744730</TimeTick>
<NodeArgs eType="User" icon="14" nRep="62" status="Information" >
<Disp><![CDATA[Action Run: 关闭销售助手页]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[销售助手]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:51]]></Time>
<TimeTick>1534744731</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[关闭页面按钮.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:51]]></Time>
<TimeTick>1534744731</TimeTick>
<NodeArgs eType="Replay" icon="19" nRep="64" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[关闭页面按钮.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[关闭页面按钮.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/20 - 13:58:52]]></Time>
<TimeTick>1534744732</TimeTick>
<NodeArgs eType="Replay" icon="19" nRep="66" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[关闭页面按钮.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[关闭页面按钮.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2018/8/20 - 13:59:54]]></Time>
<TimeTick>1534744794</TimeTick>
<NodeArgs eType="Replay" icon="19" nRep="71" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[关闭页面按钮.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="18" nRep="63" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[销售助手]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj ><![CDATA[是否正常关闭销售助手页]]></Obj>
<Details ><![CDATA[已经关闭!]]></Details>
<Time><![CDATA[2018/8/20 - 13:59:54]]></Time>
<TimeTick>1534744794</TimeTick>
<NodeArgs eType="User" icon="14" nRep="72" status="Passed" Source="Action1 [EC10_销售助手]" SourceLine="-1" >
<Disp><![CDATA[是否正常关闭销售助手页]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2018/8/20 - 13:58:50" eTime="2018/8/20 - 13:59:54" passed="1" failed="0" warnings="0" ><Param ><ParamName><![CDATA[Action]]></ParamName><ParamVal><![CDATA[关闭销售助手页]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="17" nRep="61" status="Passed" >
<Disp><![CDATA[Action1 [EC10_销售助手] Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="2018/8/20 - 13:58:31" eTime="2018/8/20 - 13:59:54" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="16" nRep="12" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="15" nRep="11" status="Passed" >
<Disp><![CDATA[008_EC主界面_销售助手_正常新建邮件计划_验证右下角弹窗 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="2018/8/20 - 13:58:30" eTime="2018/8/20 - 13:59:54" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="12" nRep="3" status="Passed" >
<Disp><![CDATA[Test 008_EC主界面_销售助手_正常新建邮件计划_验证右下角弹窗 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>