<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="HP Unified Functional Testing" productVer="12.0" os="Windows 7" host="RD-ZHANGYANG"><DocLocation><![CDATA[D:\QTP_EC10\003_EC主界面_创建EC群_正常完成创建并退出]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[003_EC主界面_创建EC群_正常完成创建并退出]]></DName>
<Res><![CDATA[Report]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="10" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj ><![CDATA[Output to global sheet]]></Obj>
<Details ><![CDATA[Name: 群名称
Value: Auto同事聊天群]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:13]]></Time>
<TimeTick>1534494373</TimeTick>
<NodeArgs eType="User" icon="11" nRep="6" status="Information" >
<Disp><![CDATA[Output to global sheet]]></Disp>
</NodeArgs>
</Step>
<Step rID="T4">
<Obj ><![CDATA[Output to global sheet]]></Obj>
<Details ><![CDATA[Name: 群公告
Value: 这是一个EC群]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:13]]></Time>
<TimeTick>1534494373</TimeTick>
<NodeArgs eType="User" icon="11" nRep="7" status="Information" >
<Disp><![CDATA[Output to global sheet]]></Disp>
</NodeArgs>
</Step>
<Step rID="T5">
<Obj ><![CDATA[Output to global sheet]]></Obj>
<Details ><![CDATA[Name: 身份验证
Value: 管理员]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:13]]></Time>
<TimeTick>1534494373</TimeTick>
<NodeArgs eType="User" icon="11" nRep="8" status="Information" >
<Disp><![CDATA[Output to global sheet]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj ><![CDATA[Output to global sheet]]></Obj>
<Details ><![CDATA[Name: EC号码
Value: 18611110001]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:13]]></Time>
<TimeTick>1534494373</TimeTick>
<NodeArgs eType="User" icon="11" nRep="9" status="Information" >
<Disp><![CDATA[Output to global sheet]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj ><![CDATA[This test is run in the EC-QA  environment by ZhangYang on RD-ZHANGYANG]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:13]]></Time>
<TimeTick>1534494373</TimeTick>
<NodeArgs eType="User" icon="11" nRep="10" status="Information" >
<Disp><![CDATA[This test is run in the EC-QA  environment by ZhangYang on RD-ZHANGYANG]]></Disp>
</NodeArgs>
</Step>
<DIter rID="T8" iterID="1" >
<Action rID="T9">
<AName><![CDATA[003_EC主界面_创建EC群_正常完成创建]]></AName>
<Action rID="T10">
<AName><![CDATA[EC_10主界面 [EC10_主面板]]]></AName>
<Step rID="T11">
<Obj ><![CDATA[Action Run: 单击创建进入创建群页]]></Obj>
<Details ><![CDATA[Data Row: 2]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:14]]></Time>
<TimeTick>1534494374</TimeTick>
<NodeArgs eType="User" icon="11" nRep="14" status="Information" >
<Disp><![CDATA[Action Run: 单击创建进入创建群页]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[EC10.0]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:15]]></Time>
<TimeTick>1534494375</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[创建按钮.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:15]]></Time>
<TimeTick>1534494375</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="17" Source="EC_10主界面 [EC10_主面板]" SourceLine="-1" >
<Disp><![CDATA[创建按钮.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[创建-创建群.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:15]]></Time>
<TimeTick>1534494375</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="19" Source="EC_10主界面 [EC10_主面板]" SourceLine="-1" >
<Disp><![CDATA[创建-创建群.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="15" nRep="16" Source="EC_10主界面 [EC10_主面板]" SourceLine="-1" >
<Disp><![CDATA[EC10.0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[创建群]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:15]]></Time>
<TimeTick>1534494375</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Window.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:15]]></Time>
<TimeTick>1534494375</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="21" Source="EC_10主界面 [EC10_主面板]" SourceLine="-1" >
<Disp><![CDATA[Window.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="15" nRep="20" Source="EC_10主界面 [EC10_主面板]" SourceLine="-1" >
<Disp><![CDATA[创建群]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj ><![CDATA[是否成功打开创建群页]]></Obj>
<Details ><![CDATA[已成功打开创建群页！]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:15]]></Time>
<TimeTick>1534494375</TimeTick>
<NodeArgs eType="User" icon="11" nRep="22" status="Passed" Source="EC_10主界面 [EC10_主面板]" SourceLine="-1" >
<Disp><![CDATA[是否成功打开创建群页]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2018/8/17 - 16:26:13" eTime="2018/8/17 - 16:26:16" passed="1" failed="0" warnings="0" ><Param ><ParamName><![CDATA[Action]]></ParamName><ParamVal><![CDATA[单击创建进入创建群页]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="14" nRep="13" status="Passed" >
<Disp><![CDATA[EC_10主界面 [EC10_主面板] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T18">
<AName><![CDATA[创建群 [EC10_创建群]]]></AName>
<Step rID="T19">
<Obj ><![CDATA[Action Run: 输入群名]]></Obj>
<Details ><![CDATA[Data Row: 1]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:16]]></Time>
<TimeTick>1534494376</TimeTick>
<NodeArgs eType="User" icon="11" nRep="25" status="Information" >
<Disp><![CDATA[Action Run: 输入群名]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[创建群]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:18]]></Time>
<TimeTick>1534494378</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[群名输入框.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["Auto同事聊天群"]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:18]]></Time>
<TimeTick>1534494378</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="28" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[群名输入框.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[群公告输入框.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["这是一个EC群"]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:20]]></Time>
<TimeTick>1534494380</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="30" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[群公告输入框.Type]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="15" nRep="27" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[创建群]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2018/8/17 - 16:26:16" eTime="2018/8/17 - 16:26:20" passed="0" failed="0" warnings="0" ><Param ><ParamName><![CDATA[Action]]></ParamName><ParamVal><![CDATA[输入群名]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="14" nRep="24" >
<Disp><![CDATA[创建群 [EC10_创建群] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T23">
<AName><![CDATA[创建群 [EC10_创建群]]]></AName>
<Step rID="T24">
<Obj ><![CDATA[Action Run: 选择只有管理员才能添加群成员]]></Obj>
<Details ><![CDATA[Data Row: 2]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:20]]></Time>
<TimeTick>1534494380</TimeTick>
<NodeArgs eType="User" icon="11" nRep="33" status="Information" >
<Disp><![CDATA[Action Run: 选择只有管理员才能添加群成员]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[创建群]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:22]]></Time>
<TimeTick>1534494382</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[选择只有管理员才能添加成员.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:22]]></Time>
<TimeTick>1534494382</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="36" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[选择只有管理员才能添加成员.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="15" nRep="35" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[创建群]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2018/8/17 - 16:26:20" eTime="2018/8/17 - 16:26:22" passed="0" failed="0" warnings="0" ><Param ><ParamName><![CDATA[Action]]></ParamName><ParamVal><![CDATA[选择只有管理员才能添加群成员]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="14" nRep="32" >
<Disp><![CDATA[创建群 [EC10_创建群] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T27">
<AName><![CDATA[创建群 [EC10_创建群]]]></AName>
<Step rID="T28">
<Obj ><![CDATA[Action Run: 点击下一步]]></Obj>
<Details ><![CDATA[Data Row: 4]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:22]]></Time>
<TimeTick>1534494382</TimeTick>
<NodeArgs eType="User" icon="11" nRep="39" status="Information" >
<Disp><![CDATA[Action Run: 点击下一步]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[创建群]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:23]]></Time>
<TimeTick>1534494383</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[下一步.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:23]]></Time>
<TimeTick>1534494383</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="42" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[下一步.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="15" nRep="41" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[创建群]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2018/8/17 - 16:26:22" eTime="2018/8/17 - 16:26:23" passed="0" failed="0" warnings="0" ><Param ><ParamName><![CDATA[Action]]></ParamName><ParamVal><![CDATA[点击下一步]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="14" nRep="38" >
<Disp><![CDATA[创建群 [EC10_创建群] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T31">
<AName><![CDATA[创建群 [EC10_创建群]]]></AName>
<Step rID="T32">
<Obj ><![CDATA[Action Run: 选择群成员完成创建]]></Obj>
<Details ><![CDATA[Data Row: 5]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:23]]></Time>
<TimeTick>1534494383</TimeTick>
<NodeArgs eType="User" icon="11" nRep="45" status="Information" >
<Disp><![CDATA[Action Run: 选择群成员完成创建]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[创建群]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:25]]></Time>
<TimeTick>1534494385</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[添加群成员名.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:25]]></Time>
<TimeTick>1534494385</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="47" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[添加群成员名.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[添加群成员名.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["18611110001"]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:26]]></Time>
<TimeTick>1534494386</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="49" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[添加群成员名.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[创建群.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[95, 180, 0]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:27]]></Time>
<TimeTick>1534494387</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="51" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[创建群.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[群创建完成按钮.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:28]]></Time>
<TimeTick>1534494388</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="53" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[群创建完成按钮.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="15" nRep="46" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[创建群]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2018/8/17 - 16:26:23" eTime="2018/8/17 - 16:26:28" passed="0" failed="0" warnings="0" ><Param ><ParamName><![CDATA[Action]]></ParamName><ParamVal><![CDATA[选择群成员完成创建]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="14" nRep="44" >
<Disp><![CDATA[创建群 [EC10_创建群] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T38">
<AName><![CDATA[创建群 [EC10_创建群]]]></AName>
<Step rID="T39">
<Obj ><![CDATA[Action Run: 检查创建成功]]></Obj>
<Details ><![CDATA[Data Row: 6]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:28]]></Time>
<TimeTick>1534494388</TimeTick>
<NodeArgs eType="User" icon="11" nRep="56" status="Information" >
<Disp><![CDATA[Action Run: 检查创建成功]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[EC10.0]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:31]]></Time>
<TimeTick>1534494391</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[搜索框.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["Auto同事聊天群"]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:31]]></Time>
<TimeTick>1534494391</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="59" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[搜索框.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[EC10.0.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[180, 100, 0]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:32]]></Time>
<TimeTick>1534494392</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="61" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[EC10.0.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[群公告检查点.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:33]]></Time>
<TimeTick>1534494393</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="62" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[群公告检查点.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="15" nRep="58" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[EC10.0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj ><![CDATA[是否正常打开群聊天页?]]></Obj>
<Details ><![CDATA[正常打开!]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:33]]></Time>
<TimeTick>1534494393</TimeTick>
<NodeArgs eType="User" icon="11" nRep="63" status="Passed" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[是否正常打开群聊天页?]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2018/8/17 - 16:26:28" eTime="2018/8/17 - 16:26:33" passed="1" failed="0" warnings="0" ><Param ><ParamName><![CDATA[Action]]></ParamName><ParamVal><![CDATA[检查创建成功]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="14" nRep="55" status="Passed" >
<Disp><![CDATA[创建群 [EC10_创建群] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T45">
<AName><![CDATA[创建群 [EC10_创建群]]]></AName>
<Step rID="T46">
<Obj ><![CDATA[Action Run: 解散群]]></Obj>
<Details ><![CDATA[Data Row: 7]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:33]]></Time>
<TimeTick>1534494393</TimeTick>
<NodeArgs eType="User" icon="11" nRep="66" status="Information" >
<Disp><![CDATA[Action Run: 解散群]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[EC10.0]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:34]]></Time>
<TimeTick>1534494394</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[群设置.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:34]]></Time>
<TimeTick>1534494394</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="68" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[群设置.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[群设置.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:35]]></Time>
<TimeTick>1534494395</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="70" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[群设置.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[解散群.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:36]]></Time>
<TimeTick>1534494396</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="72" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[解散群.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[确定.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:37]]></Time>
<TimeTick>1534494397</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="74" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[确定.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="15" nRep="67" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[EC10.0]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2018/8/17 - 16:26:33" eTime="2018/8/17 - 16:26:37" passed="0" failed="0" warnings="0" ><Param ><ParamName><![CDATA[Action]]></ParamName><ParamVal><![CDATA[解散群]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="14" nRep="65" >
<Disp><![CDATA[创建群 [EC10_创建群] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T52">
<AName><![CDATA[创建群 [EC10_创建群]]]></AName>
<Step rID="T53">
<Obj ><![CDATA[Action Run: 检查解散成功]]></Obj>
<Details ><![CDATA[Data Row: 8]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:37]]></Time>
<TimeTick>1534494397</TimeTick>
<NodeArgs eType="User" icon="11" nRep="77" status="Information" >
<Disp><![CDATA[Action Run: 检查解散成功]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[EC10.0]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:40]]></Time>
<TimeTick>1534494400</TimeTick>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[搜索框.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["Auto同事聊天群"]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:40]]></Time>
<TimeTick>1534494400</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="80" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[搜索框.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[解散后检查点.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:41]]></Time>
<TimeTick>1534494401</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="81" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[解散后检查点.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="15" nRep="79" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[EC10.0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj ><![CDATA[是否正常解散群?]]></Obj>
<Details ><![CDATA[解散成功!]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:41]]></Time>
<TimeTick>1534494401</TimeTick>
<NodeArgs eType="User" icon="11" nRep="82" status="Passed" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[是否正常解散群?]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[EC10.0]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:42]]></Time>
<TimeTick>1534494402</TimeTick>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[清除搜索.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/8/17 - 16:26:42]]></Time>
<TimeTick>1534494402</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="85" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[清除搜索.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="15" nRep="84" Source="创建群 [EC10_创建群]" SourceLine="-1" >
<Disp><![CDATA[EC10.0]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2018/8/17 - 16:26:37" eTime="2018/8/17 - 16:26:42" passed="1" failed="0" warnings="0" ><Param ><ParamName><![CDATA[Action]]></ParamName><ParamVal><![CDATA[检查解散成功]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="14" nRep="76" status="Passed" >
<Disp><![CDATA[创建群 [EC10_创建群] Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="2018/8/17 - 16:26:13" eTime="2018/8/17 - 16:26:43" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="13" nRep="12" status="Passed" >
<Disp><![CDATA[003_EC主界面_创建EC群_正常完成创建 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="12" nRep="11" status="Passed" >
<Disp><![CDATA[003_EC主界面_创建EC群_正常完成创建并退出 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="2018/8/17 - 16:26:12" eTime="2018/8/17 - 16:26:43" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="9" nRep="3" status="Passed" >
<Disp><![CDATA[Test 003_EC主界面_创建EC群_正常完成创建并退出 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>